#################################################################
## System
#################################################################

        ##########################################################
        ## Set Weather Mode on Start
        ##########################################################

- alias: System - Set Weather Mode on Start

  trigger:
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - delay: 00:02:00
    - service: switch.turn_on
      entity_id:
        - switch.summer_mode
#    - service: switch.turn_on
#      entity_id:
#        - switch.winter_mode
#    - service: switch.turn_on
#      entity_id:
#        - switch.spring_fall_mode

        ##########################################################
        ## Delay HomeKit Start
        ##########################################################

- alias: System - Delay HomeKit Start

  trigger:
    - platform: homeassistant
      event: start


  action:
    - delay: 00:02:00
    - service: homekit.start

        #################################################################
        ## Weather Lookup Failing
        #################################################################

- alias: Notification Text - Weather Lookup Failing

  trigger:
    - platform: state
      entity_id: sensor.dark_sky_humidity
      to: 'unknown'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Weather Lookup Problem!

        #################################################################
        ## NAS Warning
        #################################################################

- alias: Notification Text - NAS Warning

  trigger:
    - platform: state
      entity_id: sensor.nas_status
      to: 'warning'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: NAS RAID Failing

        ##########################################################
        ## UPS Power Loss Alert
        ##########################################################

- alias: Notification Text - UPS Power Loss Alert

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_input_voltage
      below: 80

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Power Outage Detected

        ##########################################################
        ## UPS Power Restored Alert
        ##########################################################

- alias: Notification Text - UPS Power Restored Alert

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_input_voltage
      above: 80

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: numeric_state
      entity_id: 'sensor.uptime'
      above: '0.01'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Power Restored

        ##########################################################
        ## UPS Low Battery Alert
        ##########################################################

- alias: Notification Text - UPS Low Battery Alert

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_battery_charge
      below: 15

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: "UPS Battery below 15%"

        ##########################################################
        ## UPS Low Runtime Alert
        ##########################################################

- alias: Notification Text - UPS Low Runtime Alert

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_battery_runtime_mins
      below: 15

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: "15 mins of UPS Battery Remaining!"

        ##########################################################
        ## Wink Relay Offline
        ##########################################################

- alias: Notification Text - Wink Relay Offline

  trigger:
    - platform: state
      entity_id: binary_sensor.wink_relay
      to: 'unavailable'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: "Wink Relay Has Crahsed, Please Restart"

        #################################################################
        ## REDACTED VPN Offline
        #################################################################

- alias: Notification Text - REDACTED VPN Offline

  trigger:
    - platform: state
      entity_id: binary_sensor.rochester_vpn
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: REDACTED VPN Offline
    - service: notify.REDACTED
      data:
        message: REDACTED Internets Appears to be Offline.

        #################################################################
        ## REDACTED VPN Online
        #################################################################

- alias: Notification Text - REDACTED VPN Online

  trigger:
    - platform: state
      entity_id: binary_sensor.rochester_vpn
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: REDACTED VPN Online
    - service: notify.REDACTED
      data:
        message: REDACTED Internets Back Online

        #################################################################
        ## REDACTED VPN Offline
        #################################################################

- alias: Notification Text - REDACTED VPN Offline

  trigger:
    - platform: state
      entity_id: binary_sensor.charleston_vpn
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: REDACTED VPN Offline
    - service: notify.REDACTED
      data:
        message: REDACTED Internets Appears to be Offline.

        #################################################################
        ## REDACTED VPN Online
        #################################################################

- alias: Notification Text - REDACTED VPN Online

  trigger:
    - platform: state
      entity_id: binary_sensor.charleston_vpn
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: REDACTED VPN Online
    - service: notify.REDACTED
      data:
        message: REDACTED Internets Back Online

        #################################################################
        ## Home Assistant Started Notification
        #################################################################

- alias: Notification Text - Home Assistant Start

  trigger:
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Home Assistant Started
