#################################################################
## Water Sensor Automations
#################################################################

        ##########################################################
        ## Send Notification for Water Detected Basement Drain
        ##########################################################

- alias: Water Works - Basement Drain Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected in Basement Drain!

        ##########################################################
        ## Send Notification for Water Detected Kitchen Sink
        ##########################################################

- alias: Water Works - Kitchen Sink Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_sink_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected Under Kitchen Sink!

        ##########################################################
        ## Send Notification for Water Detected Bathroom Sink
        ##########################################################

- alias: Water Works - Bathroom Sink Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_sink_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected Under Bathroom Sink!

        ##########################################################
        ## Send Notification for Water Detected Basement Door
        ##########################################################

- alias: Water Works - Basement Door Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_door_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected by Basement Door!

        ##########################################################
        ## Send Notification for Water Detected Upstairs Bathroom
        ##########################################################

- alias: Water Works - Upstairs Bathroom Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_bathrooom_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected in Upstairs Bathroom!

        ##########################################################
        ## Send Notification for Water Detected by Water Heater
        ##########################################################

- alias: Water Works - Water Heater Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.water_heater_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected by Water Heater!

        ##########################################################
        ## Send Notification for Water Detected under Utility Sink
        ##########################################################

- alias: Water Works - Utility Sink Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.utility_sink_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected Under Utility Sink!

        ##########################################################
        ## Send Notification for Water Detected behind Washing Machine
        ##########################################################

- alias: Water Works - Washing Machine Water Sensor Text Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected by Washing Machine!

        ##########################################################
        ## Send Notification for Water Detected Sump Pump
        ##########################################################

- alias: Water Works - Sump Pump Water Sensor Send Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.sump_pump_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Detected in Sump Pump!

        ##########################################################
        ## Flash Lights when Water Detected
        ##########################################################

- alias: Water Works - Sound Alarm When Water Detected Lights

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_sink_water_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bathroom_sink_water_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.upstairs_bathrooom_water_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.utility_sink_water_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       brightness_pct: 100
       color_name: "blue"
    - service: light.turn_on
      entity_id:
        - light.hue_lights
      data:
       flash: long

        ##########################################################
        ## Basement Drain Water Sensor Audio Notification
        ##########################################################

- alias: Water Works - Basement Drain Water Sensor Audio Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '.9'
          what: 'Water Detected in Basement Drain! Shutting Off Water Supply'

        ##########################################################
        ## Kitchen Sink Water Sensor Audio Notification
        ##########################################################

- alias: Water Works - Kitchen Sink Water Sensor Audio Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_sink_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '.9'
          what: 'Water Detected Under Kitchen Sink! Shutting Off Water Supply'

        ##########################################################
        ## Bathroom Sink Water Sensor Audio Notification
        ##########################################################

- alias: Water Works - Bathroom Sink Water Sensor Audio Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_sink_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '.9'
          what: 'Water Detected Under Bathroom Sink! Shutting Off Water Supply'

        ##########################################################
        ## Upstairs Bathroom Sink Water Sensor Audio Notification
        ##########################################################

- alias: Water Works - Upstairs Bathroom Sink Water Sensor Audio Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.upstairs_bathrooom_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '.9'
          what: 'Water Detected In Upstairs Bathroom! Shutting Off Water Supply'

        ##########################################################
        ## Utility Sink Water Sensor Audio Notification
        ##########################################################

- alias: Water Works - Utility Sink Water Sensor Audio Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.utility_sink_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '.9'
          what: 'Water Detected Under Utility Sink! Shutting Off Water Supply'

        ##########################################################
        ## Washing Machine Water Sensor Audio Notification
        ##########################################################

- alias: Water Works - Washing Machine Water Sensor Audio Notification

  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.sonos_living_room'
          where: 'media_player.sonos_media_center, media_player.sonos_living_room, media_player.sonos_dining_room, media_player.sonos_kitchen, media_player.sonos_bathroom, media_player.sonos_bedroom, media_player.sonos_USER1s_office, media_player.sonos_USER2s_office, media_player.sonos_basement'
          volume: '.9'
          what: 'Water Detected by Washing Machine! Shutting Off Water Supply'

        ##########################################################
        ## Shut Off Water Main When Water Detected
        ##########################################################

- alias: Water Works - Shut Off Water Main When Water Detected

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_sink_water_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bathroom_sink_water_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.upstairs_bathrooom_water_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.utility_sink_water_sensor
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.washing_machine_water_sensor
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.water_main

        ##########################################################
        ## Shut Off Water Main When Vacation Mode On
        ##########################################################

- alias: Water Works - Shut Off Water Main When Vacation Mode On

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.water_main

        ##########################################################
        ## Turn On Water Main When Vacation Mode Off
        ##########################################################

- alias: Water Works - Shut On Water Main When Vacation Mode Off

  trigger:
    - platform: state
      entity_id: input_boolean.vacation_mode
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: input_boolean.disable_water_automations
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.water_main

        ##########################################################
        ## Send Notification for Water Main Turned Off
        ##########################################################

- alias: Water Works - Send Notification for Water Main Turned Off

  trigger:
    - platform: state
      entity_id: switch.water_main
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Main Has Been Shut Off!
    - service: notify.ios_USER2s_iphone
      data:
        message: Water Main Has Been Shut Off!

        ##########################################################
        ## Send Notification for Water Main Turned On
        ##########################################################

- alias: Water Works - Send Notification for Water Main Turned On

  trigger:
    - platform: state
      entity_id: switch.water_main
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.ios_USER1s_iphone
      data:
        message: Water Main Has Been Turned Back On
    - service: notify.ios_USER2s_iphone
      data:
        message: Water Main Has Been Turned Back On.
