#################################################################
## Weather Based Automations
#################################################################

        ##########################################################
        ## Turn Globe Blue when Raining
        ##########################################################

- alias: Weather - Turn Globe Blue when Raining

  trigger:
    - platform: state
      entity_id: weather.REDACTED
      to: 'rainy'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: light.globe
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
        color_name: blue
        brightness_pct: 100
        transition: 30

        ##########################################################
        ## Reset Globe when Not Raining
        ##########################################################

- alias: Weather - Turn Globe Blue when Raining

  trigger:
    - platform: state
      entity_id: weather.REDACTED
      from: 'rainy'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: light.globe
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
        brightness_pct: 20
        color_temp: 366

        ##########################################################
        ## Set Globe Blue when On and Raining
        ##########################################################

- alias: Weather - Set Globe Blue when On and Raining

  trigger:
    - platform: state
      entity_id: light.globe
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: weather.REDACTED
      state: 'rainy'
    - condition: state
      entity_id: input_boolean.livingroom_rainbow
      state: 'off'
    - condition: state
      entity_id: input_boolean.interior_holiday
      state: 'off'
    - condition: state
      entity_id: input_boolean.alarm_tripped
      state: 'off'
    - condition: state
      entity_id: binary_sensor.basement_drain_water_sensor_liquid_detected
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
        color_name: blue
        brightness_pct: 100
        transition: 90
